/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package week6_calculatorwithgui;

import javax.swing.JOptionPane;

/**
 *
 * @author trion
 */

    public class CalculatorGUI extends javax.swing.JFrame {
    private Calculator myCalculator;
    
      private int operand1;
      private int  operand2;
    
    /**
     * Creates new form Calculator
     */
    public CalculatorGUI(Calculator inCalculator) {
        initComponents(); 
        myCalculator = inCalculator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        operand1Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        operand2Label = new javax.swing.JLabel();
        operand2TextField = new javax.swing.JTextField();
        addButton = new javax.swing.JRadioButton();
        subtractButton = new javax.swing.JRadioButton();
        multiplyButton = new javax.swing.JRadioButton();
        divideButton = new javax.swing.JRadioButton();
        resultDisplayLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        operand1TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        operand1Label.setText("Operand 1 ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Simple Calculator");

        operand2Label.setText("Operand 2 ");

        operand2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operand2TextFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(addButton);
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(subtractButton);
        subtractButton.setText("Subtract");
        subtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(multiplyButton);
        multiplyButton.setText("Multiply");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(divideButton);
        divideButton.setText("Divide");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        resultDisplayLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        resultLabel.setText("Result:");

        operand1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operand1TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resultDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(operand1Label)
                                            .addComponent(operand2Label))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(operand1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(operand2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resultLabel)
                                            .addComponent(addButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(subtractButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(multiplyButton)))
                                .addGap(18, 18, 18)
                                .addComponent(divideButton)))))
                .addGap(104, 104, 104))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operand1Label)
                    .addComponent(operand1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operand2Label)
                    .addComponent(operand2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(subtractButton)
                    .addComponent(multiplyButton)
                    .addComponent(divideButton))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        getOperands();
        int result = myCalculator.add(operand1,operand2);
        resultDisplayLabel.setText(convertResultToString(result));
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void subtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractButtonActionPerformed
        getOperands();
        int result = myCalculator.subtract(operand1, operand2);
        resultDisplayLabel.setText(convertResultToString(result));
    }//GEN-LAST:event_subtractButtonActionPerformed

    private void operand1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operand1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operand1TextFieldActionPerformed

    private void operand2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operand2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operand2TextFieldActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed

        getOperands();
        int result = myCalculator.multiply(operand1, operand2);
        resultDisplayLabel.setText(convertResultToString(result));
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        getOperands();
        try {
        int result = myCalculator.divide(operand1, operand2);
        resultDisplayLabel.setText(convertResultToString(result));
        }
        catch ( IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_divideButtonActionPerformed

    /**
     * Get the operands that the user entered on the screen and convert them to 
     * integers so that we can do calculations
     */
    private void getOperands()  {
        try {
        operand1 = Integer.parseInt(operand1TextField.getText());
        operand2 = Integer.parseInt(operand2TextField.getText()); }
        
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Invalid operand entered. Operands must be numeric.");
        }
     }
    
    /**
     * Convert the calculated result to a string for displaying on the user interface
     * @param result - the result of the calculation
     * @return a string with the value of the result for the purpose of display on the user interface
     */
    private String convertResultToString(int result) {
        return result + "";
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton divideButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton multiplyButton;
    private javax.swing.JLabel operand1Label;
    private javax.swing.JTextField operand1TextField;
    private javax.swing.JLabel operand2Label;
    private javax.swing.JTextField operand2TextField;
    private javax.swing.JLabel resultDisplayLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JRadioButton subtractButton;
    // End of variables declaration//GEN-END:variables
}


